### ISSUE TITLE
.fit attribute

### ISSUE THREAD

**Issue by sethubhargavmeruga** [ColasGael/Machine-Learning-for-Solar-Energy-Prediction#3]
'function' object has no attribute 'fit' . Please resolve this issue.

**Comment by adele-k02** [comment]
Hi sethubhargavmeruga,

Many thanks for raising this issue! Can you please tell me which code you're running? That would help me identify what the problem might be. Thanks again :-) -Adele

**Comment by sethubhargavmeruga** [comment]
I'm running the recurrent neural network file , there is an issue with fit attribute. the following is the compiler result. I have installed numpy yet this is the error.
[Running] python -u "d:\Btech Project\Machine-Learning-for-Solar-Energy-Prediction-master\Recurrent Neural Network\rnn.py"
Traceback (most recent call last):
  File "d:\Btech Project\Machine-Learning-for-Solar-Energy-Prediction-master\Recurrent Neural Network\rnn.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

[Done] exited with code=1 in 0.396 seconds

**Comment by sethubhargavmeruga** [comment]
There is also a problem with the weighted linear regression file. the following is the error :
Error using datetime (line 556)
Numeric input data must be a matrix with three or six columns, or else three or six separate numeric
arrays. You can also create datetimes from a single numeric array using the 'ConvertFrom' parameter.

Error in weighted_linear_regression (line 18)
timeline = datetime(timeline,'Format','dd-MM-yyyy'); % the dates of every example of the test set

**Comment by sethubhargavmeruga** [comment]
Please help me and kindly guide me through the project as this is really important for my credits. thanks in advance. 
If willing to email : sbm11@iitbbs.ac.in

**Comment by adele-k02** [comment]
Cool - what python version are you running? Thanks :)

**Comment by sethubhargavmeruga** [comment]
I'm using the 3.8 version .

**Comment by ColasGael** [comment]
For the weighted linear regression:
The datetime parsing works on my machine (Matlab 8.6) with our `weather_test_timeline.csv`

But it doesn't really matter if it does not work on your machine: this parsing is only use for plotting on a time axis.
You can create your own parsing or your own plots, no need to use ours.
You can remove the following lines and the computations should still as a charm.

https://github.com/ColasGael/Machine-Learning-for-Solar-Energy-Prediction/blob/master/Weighted%20Linear%20Regression/weighted_linear_regression.m#L16-L18
https://github.com/ColasGael/Machine-Learning-for-Solar-Energy-Prediction/blob/master/Weighted%20Linear%20Regression/weighted_linear_regression.m#L96-L128
https://github.com/ColasGael/Machine-Learning-for-Solar-Energy-Prediction/blob/master/Weighted%20Linear%20Regression/weighted_linear_regression.m#L135-L163
